iso_3166_1_alpha_3 = {
    'AFG': 'Afghanistan',
    'ALA': 'Îles Åland',
    'ALB': 'Albanie',
    'DZA': 'Algérie',
    'ASM': 'Samoa américaines',
    'AND': 'Andorre',
    'AGO': 'Angola',
    'AIA': 'Anguilla',
    'ATA': 'Antarctique',
    'ATG': 'Antigua-et-Barbuda',
    'ARG': 'Argentine',
    'ARM': 'Arménie',
    'ABW': 'Aruba',
    'AUS': 'Australie',
    'AUT': 'Autriche',
    'AZE': 'Azerbaïdjan',
    'BHS': 'Bahamas',
    'BHR': 'Bahreïn',
    'BGD': 'Bangladesh',
    'BRB': 'Barbade',
    'BLR': 'Bélarus',
    'BEL': 'Belgique',
    'BLZ': 'Belize',
    'BEN': 'Bénin',
    'BMU': 'Bermudes',
    'BTN': 'Bhoutan',
    'BOL': 'Bolivie',
    'BES': 'Bonaire, Saint-Eustache et Saba',
    'BIH': 'Bosnie-Herzégovine',
    'BWA': 'Botswana',
    'BVT': 'Île Bouvet',
    'BRA': 'Brésil',
    'IOT': "Territoire britannique de l'océan Indien",
    'BRN': 'Brunéi Darussalam',
    'BGR': 'Bulgarie',
    'BFA': 'Burkina Faso',
    'BDI': 'Burundi',
    'CPV': 'Cap-Vert',
    'KHM': 'Cambodge',
    'CMR': 'Cameroun',
    'CAN': 'Canada',
    'CYM': 'Îles Caïmans',
    'CAF': 'République centrafricaine',
    'TCD': 'Tchad',
    'CHL': 'Chili',
    'CHN': 'Chine',
    'CXR': 'Île Christmas',
    'CCK': 'Îles Cocos',
    'COL': 'Colombie',
    'COM': 'Comores',
    'COG': 'Congo',
    'COD': 'République démocratique du Congo',
    'COK': 'Îles Cook',
    'CRI': 'Costa Rica',
    'CIV': "Côte d'Ivoire",
    'HRV': 'Croatie',
    'CUB': 'Cuba',
    'CUW': 'Curaçao',
    'CYP': 'Chypre',
    'CZE': 'République tchèque',
    'DNK': 'Danemark',
    'DJI': 'Djibouti',
    'DMA': 'Dominique',
    'DOM': 'République dominicaine',
    'ECU': 'Équateur',
    'EGY': 'Égypte',
    'SLV': 'El Salvador',
    'GNQ': 'Guinée équatoriale',
    'ERI': 'Érythrée',
    'EST': 'Estonie',
    'SWZ': 'Eswatini',
    'ETH': 'Éthiopie',
    'FLK': 'Îles Malouines',
    'FRO': 'Îles Féroé',
    'FJI': 'Fidji',
    'FIN': 'Finlande',
    'FRA': 'France',
    'GUF': 'Guyane française',
    'PYF': 'Polynésie française',
    'ATF': 'Terres australes françaises',
    'GAB': 'Gabon',
    'GMB': 'Gambie',
    'GEO': 'Géorgie',
    'DEU': 'Allemagne',
    'GHA': 'Ghana',
    'GIB': 'Gibraltar',
    'GRC': 'Grèce',
    'GRL': 'Groenland',
    'GRD': 'Grenade',
    'GLP': 'Guadeloupe',
    'GUM': 'Guam',
    'GTM': 'Guatemala',
    'GGY': 'Guernesey',
    'GIN': 'Guinée',
    'GNB': 'Guinée-Bissau',
    'GUY': 'Guyana',
    'HTI': 'Haïti',
    'HMD': 'Îles Heard-et-MacDonald',
    'VAT': 'Saint-Siège (État de la Cité du Vatican)',
    'HND': 'Honduras',
    'HKG': 'Hong Kong',
    'HUN': 'Hongrie',
    'ISL': 'Islande',
    'IND': 'Inde',
    'IDN': 'Indonésie',
    'IRN': 'Iran',
    'IRQ': 'Irak',
    'IRL': 'Irlande',
    'IMN': 'Île de Man',
    'ISR': 'Israël',
    'ITA': 'Italie',
    'JAM': 'Jamaïque',
    'JPN': 'Japon',
    'JEY': 'Jersey',
    'JOR': 'Jordanie',
    'KAZ': 'Kazakhstan',
    'KEN': 'Kenya',
    'KIR': 'Kiribati',
    'PRK': 'Corée du Nord',
    'KOR': 'Corée du Sud',
    'KWT': 'Koweït',
    'KGZ': 'Kirghizistan',
    'LAO': 'Laos',
    'LVA': 'Lettonie',
    'LBN': 'Liban',
    'LSO': 'Lesotho',
    'LBR': 'Libéria',
    'LBY': 'Libye',
    'LIE': 'Liechtenstein',
    'LTU': 'Lituanie',
    'LUX': 'Luxembourg',
    'MAC': 'Macao',
    'MKD': 'Macédoine',
    'MDG': 'Madagascar',
    'MWI': 'Malawi',
    'MYS': 'Malaisie',
    'MDV': 'Maldives',
    'MLI': 'Mali',
    'MLT': 'Malte',
    'MHL': 'Îles Marshall',
    'MTQ': 'Martinique',
    'MRT': 'Mauritanie',
    'MUS': 'Maurice',
    'MYT': 'Mayotte',
    'MEX': 'Mexique',
    'FSM': 'Micronésie',
    'MDA': 'Moldavie',
    'MCO': 'Monaco',
    'MNG': 'Mongolie',
    'MNE': 'Monténégro',
    'MSR': 'Montserrat',
    'MAR': 'Maroc',
    'MOZ': 'Mozambique',
    'MMR': 'Myanmar',
    'NAM': 'Namibie',
    'NRU': 'Nauru',
    'NPL': 'Népal',
    'NLD': 'Pays-Bas',
    'NCL': 'Nouvelle-Calédonie',
    'NZL': 'Nouvelle-Zélande',
    'NIC': 'Nicaragua',
    'NER': 'Niger',
    'NGA': 'Nigeria',
    'NIU': 'Niue',
    'NFK': 'Île Norfolk',
    'MNP': 'Îles Mariannes du Nord',
    'NOR': 'Norvège',
    'OMN': 'Oman',
    'PAK': 'Pakistan',
    'PLW': 'Palaos',
    'PSE': 'Territoire palestinien',
    'PAN': 'Panama',
    'PNG': 'Papouasie-Nouvelle-Guinée',
    'PRY': 'Paraguay',
    'PER': 'Pérou',
    'PHL': 'Philippines',
    'PCN': 'Îles Pitcairn',
    'POL': 'Pologne',
    'PRT': 'Portugal',
    'PRI': 'Porto Rico',
    'QAT': 'Qatar',
    'REU': 'La Réunion',
    'ROU': 'Roumanie',
    'RUS': 'Russie',
    'RWA': 'Rwanda',
    'BLM': 'Saint-Barthélemy',
    'SHN': 'Sainte-Hélène',
    'KNA': 'Saint-Christophe-et-Niévès',
    'LCA': 'Sainte-Lucie',
    'MAF': 'Saint-Martin',
    'SPM': 'Saint-Pierre-et-Miquelon',
    'VCT': 'Saint-Vincent-et-les-Grenadines',
    'WSM': 'Samoa',
    'SMR': 'Saint-Marin',
    'STP': 'Sao Tomé-et-Principe',
    'SAU': 'Arabie saoudite',
    'SEN': 'Sénégal',
    'SRB': 'Serbie',
    'SYC': 'Seychelles',
    'SLE': 'Sierra Leone',
    'SGP': 'Singapour',
    'SXM': 'Saint-Martin',
    'SVK': 'Slovaquie',
    'SVN': 'Slovénie',
    'SLB': 'Îles Salomon',
    'SOM': 'Somalie',
    'ZAF': 'Afrique du Sud',
    'SGS': 'Géorgie du Sud-et-les Îles Sandwich du Sud',
    'SSD': 'Soudan du Sud',
    'ESP': 'Espagne',
    'LKA': 'Sri Lanka',
    'SDN': 'Soudan',
    'SUR': 'Suriname',
    'SJM': 'Svalbard et Île Jan Mayen',
    'SWZ': 'Swaziland',
    'SWE': 'Suède',
    'CHE': 'Suisse',
    'SYR': 'Syrie',
    'TWN': 'Taïwan',
    'TJK': 'Tadjikistan',
    'TZA': 'Tanzanie',
    'THA': 'Thaïlande',
    'TLS': 'Timor oriental',
    'TGO': 'Togo',
    'TKL': 'Tokelau',
    'TON': 'Tonga',
    'TTO': 'Trinité-et-Tobago',
    'TUN': 'Tunisie',
    'TUR': 'Turquie',
    'TKM': 'Turkménistan',
    'TCA': 'Îles Turques-et-Caïques',
    'TUV': 'Tuvalu',
    'UGA': 'Ouganda',
    'UKR': 'Ukraine',
    'ARE': 'Émirats arabes unis',
    'GBR': 'Royaume-Uni',
    'USA': 'États-Unis',
    'UMI': 'Îles mineures éloignées des États-Unis',
    'URY': 'Uruguay',
    'UZB': 'Ouzbékistan',
    'VUT': 'Vanuatu',
    'VEN': 'Venezuela',
    'VNM': 'Vietnam',
    'VGB': 'Îles Vierges britanniques',
    'VIR': 'Îles Vierges des États-Unis',
    'WLF': 'Wallis-et-Futuna',
    'ESH': 'Sahara occidental',
    'YEM': 'Yémen',
    'ZMB': 'Zambie',
    'ZWE': 'Zimbabwe'
}